### ISSUE TITLE
Special Matrix Transpose

### ISSUE THREAD

**Issue by Stivanification** [JuliaMatrices/SpecialMatrices.jl#10]
Hi,

When I try to transpose a Vandermonde matrix, I get the following error message: 

ERROR: ctranspose not implemented for SpecialMatrices.Vandermonde{Float64}. Consider adding parentheses, e.g. A_(B_C') instead of A_B_C' to avoid explicit calculation of the transposed matrix.

writing it in Parentheses didnt help.

**Comment by jiahao** [comment]
For now the only thing that can be done is `ctranspose(full(A))`.
