### ISSUE TITLE
Move to JuliaMath?

### ISSUE THREAD

**Issue by jiahao** [JuliaMatrices/SpecialMatrices.jl#12]
@JuliaMath

**Comment by ChrisRackauckas** [comment]
I think it would be a good idea. I didn't know that this existed until I went on a package searching spree. Although it's not integrated with the other packages right now, I think the real power of this package will come from putting special dispatches on these types to use with things like IterativeSolvers.jl  (for matrix-free methods), in which case the integration will definitely warrant the move.

**Comment by ivanslapnicar** [comment]
It is exactly where the power lies. Check the [notebook](https://github.com/ivanslapnicar/GIAN-Applied-NLA-Course/blob/master/src/Module%20C%20-%20Applications/L14%20Signal%20Decomposition%20Using%20EVD%20of%20Hankel%20Matrices.ipynb) for an example of using Hankel() type, fast multiply via fft, and LinearMaps.jl to compute 40 eigenvalues of a 50001x50001 matrix in 6-7 seconds.

**Comment by ChrisRackauckas** [comment]
I think it would be a good idea to migrate, since it would help others join in maintenance to do things like https://github.com/jiahao/SpecialMatrices.jl/issues/15.

**Comment by simonbyrne** [comment]
Let's do it: @jiahao you should already have the appropriate privileges.

**Comment by jiahao** [comment]
Well, we didn't exactly end up in JuliaMath, but JuliaMatrices is also a good home.
