### ISSUE TITLE
Please add a tag to current master and update METADATA

### ISSUE THREAD

**Issue by fp4code** [JuliaMatrices/SpecialMatrices.jl#15]
As seen at http://pkg.julialang.org/detail/SpecialMatrices.html page, Pkg.test("SpecialMatrices") fails.

Master is OK for both julia-0.4 and julia-0.5

```julia
Pkg.checkout("SpecialMatrices")
Pkg.test("SpecialMatrices") # OK

Pkg.free("SpecialMatrices")
Pkg.test("SpecialMatrices") # ERROR
```

Please add a tag to the current master commit,  https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/SpecialMatrices is 3 years old !

**Comment by ChrisRackauckas** [comment]
Second this. There should really be a new tag.
