### ISSUE TITLE
Error Companion Matrix

### ISSUE THREAD

**Issue by angadrandhawa** [JuliaMatrices/SpecialMatrices.jl#18]
I get the following error when trying to create the companion Matrix. Below is the error that I am getting. I am using the same example as specified in the example i.e

`A=Companion([3,2,1])`

Error displaying SpecialMatrices.Companion{Float64}: MethodError: isassigned(::SpecialMatrices.Companion{Float64}, ::Int64, ::Int64) is ambiguous. Candidates:
  isassigned(C::SpecialMatrices.Companion, i, j) at /Users/chahatsharma/.julia/v0.5/SpecialMatrices/src/companion.jl:18
  isassigned(a::AbstractArray, i::Int64...) at abstractarray.jl:185
 in alignment(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::SpecialMatrices.Companion{Float64}, ::Array{Int64,1}, ::Array{Int64,1}, ::Int64, ::Int64, ::Int64) at show.jl:1277
 in print_matrix(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::SpecialMatrices.Companion{Float64}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64) at show.jl:1407
 in print_matrix(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::SpecialMatrices.Companion{Float64}, ::String, ::String, ::String) at show.jl:1379
 in #showarray#342(::Bool, ::Function, ::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::SpecialMatrices.Companion{Float64}, ::Bool) at show.jl:1618
 in (::Juno.##1#2{SpecialMatrices.Companion{Float64}})(::Base.AbstractIOBuffer{Array{UInt8,1}}) at types.jl:11
 in #sprint#316(::Void, ::Function, ::Int64, ::Function) at io.jl:37
 in Type at types.jl:51 [inlined]
 in Type at types.jl:52 [inlined]
 in render(::Juno.Console, ::SpecialMatrices.Companion{Float64}) at types.jl:16
 in render′(::Juno.Console, ::SpecialMatrices.Companion{Float64}) at errors.jl:89
 in (::Atom.##65#68)() at eval.jl:104
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60

**Comment by ivanslapnicar** [comment]
Please make sure that you are using the latest version,
Pkg.checkout("SpecialMatrices").

**Comment by angadrandhawa** [comment]
I installed it just 3 days back, how can I be using an outdated package.

Pkg.add("SpecialMatrices")

**Comment by ivanslapnicar** [comment]
Sorry, we did not tag the latest version since there are still some modifications planned.


---- angadrandhawa je napisao ----


I installed it just 3 days back, how can I be using an outdated package.

Pkg.add("SpecialMatrices")
