### ISSUE TITLE
Extending Circulant Functionality

### ISSUE THREAD

**Issue by willtebbutt** [JuliaMatrices/SpecialMatrices.jl#21]
I would like to see the functionality associated with the circulant matrices be extended and would therefore like to understand whether that's something people are interested in pursuing. I made #13 a while ago (sorry about that, it was rude to submit such a large PR like that without discussing any of it first) which outlined the kind of things I'm interested in achieving.

It would be useful for my work if there is support for the addition, multiplication, (log) determinant computation and transposition of circulant matrices, since they can all be performed efficiently - there are other operations for which circulant matrices admit efficient computation but these would be a good start. Also, extending multiplication of circulant matrices by dense matrices / vectors from just matrix-vector to matrix-matrix seems reasonable as analogous performance gains are made.

Similarly, the eigendecomposition of circulant matrices can be represented in `O(N)` time, since the eigenvector matrix is just the DFT matrix which requires `O(1)` memory (which raises the question of whether it's worth also supporting the DFT matrix for syntactic convenience).

Is this kind of extension of interest?

**Comment by devmotion** [comment]
ToeplitzMatrices.jl has better support for Toeplitz and circulant matrices and already supports some of the suggested operations (see also https://github.com/JuliaMatrices/SpecialMatrices.jl/issues/23 and https://github.com/JuliaMatrices/SpecialMatrices.jl/pull/40). I suggest improving the support for circulant matrices (e.g., by implementing `logdet`) in ToeplitzMatrices but not in SpecialMatrices.
