### ISSUE TITLE
Julia 1.1 Compatibility

### ISSUE THREAD

**Issue by vincentcp** [JuliaMatrices/SpecialMatrices.jl#27]
Can a Julia 1.1 compatible release be created? 
Now I can only add SpecialMatrices to Julia 1.1 using `dev`.

**Comment by ivanslapnicar** [comment]
Dear Vincent,


could you try

pkg> add SpecialMatrices#master


Ivan


Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803


________________________________
Šalje: vincentcp <notifications@github.com>
Poslano: 29. siječnja 2019. 16:41
Prima: JuliaMatrices/SpecialMatrices.jl
Kopija: Subscribed
Predmet: [JuliaMatrices/SpecialMatrices.jl] Julia 1.1 Compatibility (#27)


Can a Julia 1.1 compatible release be created?
Now I can only add SpecialMatrices to Julia 1.1 using dev.

**Comment by vincentcp** [comment]
Thank you, 
Your changes made the master compatible.

**Comment by ivanslapnicar** [comment]
The commit that did it is by  @ludvigak so he should get the

credits and the thanks.


Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803


________________________________
Šalje: vincentcp <notifications@github.com>
Poslano: 30. siječnja 2019. 15:52
Prima: JuliaMatrices/SpecialMatrices.jl
Kopija: Ivan Slapničar; Comment
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Julia 1.1 Compatibility (#27)


Thank you,
Your changes made the master compatible.
