### ISSUE TITLE
Polynomials 1.0 no longer exports Poly

### ISSUE THREAD

**Issue by bocc** [JuliaMatrices/SpecialMatrices.jl#35]
Hello,

a current installation of SpecialMatrices pulls in Polynomials 1.0.0 as a dependency, which no longer exports the Poly type (it has two poly types, Polynomial and PolyCompat now), which causes precompilation to fail.

**Comment by mkitti** [comment]
This seems to have been fixed on master as of 5416215

**Comment by bocc** [comment]
Great, thank you! 👍
