### ISSUE TITLE
Failed to precompile SpecialMatrices

### ISSUE THREAD

**Issue by sanchezcarlosjr** [JuliaMatrices/SpecialMatrices.jl#37]
# Bug
WARNING: Compat.LinearAlgebra is deprecated, use LinearAlgebra instead.

# Context
Julia Version 1.4.2

**Comment by anandijain** [comment]
Getting a similar(?) bug: 
```julia 
[ Info: Precompiling SpecialMatrices [928aab9d-ef52-54ac-8ca1-acd7ca42c160]
ERROR: LoadError: LoadError: UndefVarError: Poly not defined
```

**Comment by ivanslapnicar** [comment]
Please add the current master:

(@v1.4) pkg> add SpecialMatrices#master


Best regards, Ivan

Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803

________________________________
Šalje: anand jain <notifications@github.com>
Poslano: 11. rujna 2020. 1:03
Prima: JuliaMatrices/SpecialMatrices.jl <SpecialMatrices.jl@noreply.github.com>
Kopija: Subscribed <subscribed@noreply.github.com>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Failed to precompile SpecialMatrices (#37)


Getting a similar(?) bug:

[ Info: Precompiling SpecialMatrices [928aab9d-ef52-54ac-8ca1-acd7ca42c160]
ERROR: LoadError: LoadError: UndefVarError: Poly not defined

**Comment by JeffFessler** [comment]
v1.0.1 is tagged now so I am closing this issue.
