### ISSUE TITLE
Possible to get a new tagged release?

### ISSUE THREAD

**Issue by ali-ramadhan** [JuliaMatrices/SpecialMatrices.jl#39]
Looks like it's been over a year with no tagged releases.

I also encountered the same bug as https://github.com/JuliaMatrices/SpecialMatrices.jl/issues/37#issuecomment-690776388 and it would be nice if `] add SpecialMatrices` just worked.

**Comment by JeffFessler** [comment]
@ivanslapnicar the change from `Poly` to `Polynomials` in 1.0.0 to 1.0.1 really deserves a new tag.
Do you need help maintaining this package?

**Comment by ivanslapnicar** [comment]
I tried to tag new version, but it did not work out. Help wouild be appreciated.

Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803

________________________________
Šalje: Jeff Fessler ***@***.***>
Poslano: 24. svibnja 2021. 2:14
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Ivan Slapničar ***@***.***>; Mention ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Possible to get a new tagged release? (#39)


@ivanslapnicar<https://github.com/ivanslapnicar> the change from Poly to Polynomials in 1.0.0 to 1.0.1 really deserves a new tag.
Do you need help maintaining this package?

**Comment by JeffFessler** [comment]
So you can either add me as a maintainer of this package or you can go to this page
https://github.com/JuliaMatrices/SpecialMatrices.jl/commit/c1d004da20e638cbc1e146dafaaffc978d7ba805
and cut and paste the register command there.  (See my example there.)
Only maintainers can run that command.

**Comment by ivanslapnicar** [comment]
Dear Jeff,

I can add you as maintainer, but I would also like to learn how to tag new version properly for my other packages.
How do I add you as maintainer?
Where do I put the command
@JuliaRegistrator<https://github.com/JuliaRegistrator>() register   ?
I think I put it somewhere sopme 5-6 months ago, but nothing happended.

Best regards, Ivan




Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803

________________________________
Šalje: Jeff Fessler ***@***.***>
Poslano: 25. svibnja 2021. 0:00
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Ivan Slapničar ***@***.***>; Mention ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Possible to get a new tagged release? (#39)


So you can either add me as a maintainer of this package or you can go to this page
c1d004d<https://github.com/JuliaMatrices/SpecialMatrices.jl/commit/c1d004da20e638cbc1e146dafaaffc978d7ba805>
and cut and paste the register command there. (See my example there.)
Only maintainers can run that command.

**Comment by JeffFessler** [comment]
To add a maintainer, go to the settings tab then click "manage access"
https://github.com/JuliaMatrices/SpecialMatrices.jl/settings/access
Then click "invite collaborator" and enter my github name
`JeffFessler`

To tag a new version, typically you go to the latest commit and then add a comment at the end.
The wording of the comment must be exactly this:
`@JuliaRegistrator() register`

For this package, the latest commit is at this url:
https://github.com/JuliaMatrices/SpecialMatrices.jl/commit/c1d004da20e638cbc1e146dafaaffc978d7ba805

Alternatively you could paste that line into as a comment in an issue.
You seem to be replying by email but you probably need to go to the github portal to do it:
https://github.com/JuliaMatrices/SpecialMatrices.jl/issues/39

**Comment by JeffFessler** [comment]
BTW, I think it will work only if there is a proper ssh key set up per instructions here:
https://github.com/JuliaRegistries/TagBot
That might be a more recent requirement (unsure)...

**Comment by devmotion** [comment]
JuliaRegistrator does not require TagBot, TagBot will just automatically add a tag when a new release is available in the Julia package registry. An SSH key is only required if you want to run other Github actions (such as building the documentation) after a new tag was added (by default, Github does not allow an action to trigger other actions).

You should also be aware of that the pull request to the package registry will not be approved if you run JuliaRegistrator with the current master branch (on a sidenote, one can also just comment on the commit that should be registered, usually I think that's a bit cleaner than comments in an issue). The registry requires compat bounds for all dependencies, as I added in the PR: https://github.com/devmotion/SpecialMatrices.jl/blob/dw/toeplitzmatrices/Project.toml

**Comment by ivanslapnicar** [comment]
Jeff, I succeeded to tag the new version. I dont have Settings button in this repository. I will see what is the problem.

Dana 24. svi 2021. 02:14 osoba Jeff Fessler ***@***.***> napisala je:

@ivanslapnicar<https://github.com/ivanslapnicar> the change from Poly to Polynomials in 1.0.0 to 1.0.1 really deserves a new tag.
Do you need help maintaining this package?

**Comment by t-bltg** [comment]
@ivanslapnicar, it seems registering a new release is not solved (I also hit https://github.com/JuliaMatrices/SpecialMatrices.jl/issues/37#issuecomment-690776388).

Can I assist in any way ?

**Comment by JeffFessler** [comment]
@dlfivefifty, since you are a member of JuliaMatrices do you have the ability to add me as a maintainer of SpecialMatrices so that I can help resolve this tagging issue?

**Comment by dlfivefifty** [comment]
@JeffFessler I've invited you to be a maintainer

**Comment by JeffFessler** [comment]
v1.0.1 is tagged now so I am closing this issue.
