### ISSUE TITLE
Please register the latestet version v2.0.1 officially

### ISSUE THREAD

**Issue by wg030** [JuliaMatrices/SpecialMatrices.jl#57]
I would be very convenient if the latest version `2.0.1` could be registered officially because the last officially registered version `2.0.0 `forces `Polynomials` to be on `v2.0.25` instead of `v.3.2.0`.

**Comment by JeffFessler** [comment]
Done:
https://github.com/JuliaRegistries/General/pull/70520

And when I `add` this package now I get `2.0.1`.

However, the "Releases" section of the home page still show 2.0.0 as the latest.  I don't understand why that would be.

**Comment by JeffFessler** [comment]
We do have TagBot installed
https://github.com/JuliaMatrices/SpecialMatrices.jl/pull/31/files
but perhaps there is an issue with the ssh key.

**Comment by ivanslapnicar** [comment]
Yes. ZagBopt is there, but I don't know which ssh keys are those and how to fix them. Help, please.

Prof. dr. sc. Ivan Slapničar
Sveučilište u Splitu / University of Split
FESB
R. Boškovića 32
HR-21000 Split
Hrvatska / Croatia
Phone: + 385 21 305893
Ured/Office: B803
________________________________
Šalje: Jeff Fessler ***@***.***>
Poslano: 18. listopada 2022. 17:37
Prima: JuliaMatrices/SpecialMatrices.jl ***@***.***>
Kopija: Subscribed ***@***.***>
Predmet: Re: [JuliaMatrices/SpecialMatrices.jl] Please register the latestet version v2.0.1 officially (Issue #57)


We do have TagBot installed
https://github.com/JuliaMatrices/SpecialMatrices.jl/pull/31/files
but perhaps there is an issue with the ssh key.
